---
version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
  pre_build:
    commands:
      - IMAGE_TAG=$(git rev-parse --short HEAD)
      - aws ecr get-login --no-include-email --region ${REGION}
  build:
    commands:
      - cp -p .env.example .env && sed -i 's/ENV='\''\/dev\/'\''/ENV='\''\/'\''/' .env
      - docker build -f docker/Dockerfile -t src_cvfl .
      - docker tag src_cvfl ${ECR_URI}:${IMAGE_TAG}
  post_build:
    commands:
      - docker push ${ECR_URI}:${IMAGE_TAG}
      - sed -i "s/<ECR_URI>/${ECR_URI}/g" ./docker/k8s/deployment.yml
      - sed -i "s/<IMAGE_TAG>/${IMAGE_TAG}/g" ./docker/k8s/deployment.yml
      - kubectl apply -f ./docker/k8s/

      

